Settings Redesign
willowtreeapps/eyespeak-ios pull request #154
Opened 2020-03-20 14:02 UTC by jsmorgan42

Changes included:
- Changing layout to have new settings re-design for iPhone & iPad
- Updating feature flag to only show available screens on the app store build
- Fixing bug on Edit my sayings screen where the gazeable buttons on the top bar were not triggering the primary action, making them not react to head tracking

<img width="175" alt="Screen Shot 2020-03-20 at 9 55 57 AM" src="https://user-images.githubusercontent.com/37670742/77170724-d5eb6f00-6a91-11ea-9144-3030b26344be.png">
<img width="400" alt="Screen Shot 2020-03-20 at 9 56 07 AM" src="https://user-images.githubusercontent.com/37670742/77170738-dbe15000-6a91-11ea-9562-fc7251f5e154.png">
<img width="400" alt="Screen Shot 2020-03-20 at 9 56 40 AM" src="https://user-images.githubusercontent.com/37670742/77170745-de43aa00-6a91-11ea-8c00-1450ca5189f9.png">
<img width="350" alt="Screen Shot 2020-03-20 at 9 57 42 AM" src="https://user-images.githubusercontent.com/37670742/77170752-e00d6d80-6a91-11ea-9d1f-499322dd97ae.png">

2020-03-20 14:21 UTC, Clstroud requested changes
Looking good, just a few suggested changes

2020-03-20 14:21 UTC, Clstroud commented on Vocable/AppConfig.swift
> +    static let showDebugOptions: Bool = {
Nice

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/Views/SettingsCollectionViewCell.swift
> +    private var disposables = Set<AnyCancellable>()
```suggestion
```

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/Views/SettingsCollectionViewCell.swift
> +
```suggestion
```

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/Views/SettingsFooterCollectionViewCell.swift
>          versionLabel.textColor = .defaultTextColor
Can the color be assigned in the xib as well? Same for the class up above

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/Views/SettingsToggleCollectionViewCell.swift
>          textLabel.textColor = .defaultTextColor
And this one

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +                                  .contactDevs(titles.contactDevs.rawValue)])
It feels redundant to have the titles _and_ the item identifiers. Can the item identifiers _be_ the titles?

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let internalLinksItemCount = dataSource.snapshot().itemIdentifiers.count - 3
Is this magic 3 avoidable?

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +    private func regularHeightWidthLayout() -> UICollectionViewLayout {
I had to think about this for a second. If this is a convention we want to use, I think I'm good with it, but I'd like both size classes to be a little more explicit for readability. e.g. `regularHeightRegularWidthLayout`. `layout_hRwR` to match IB notation? Not sure.

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +                                                                      count: 2)
Same thing here, what does this 2 represent? I presume a column count

2020-03-20 14:21 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +//    }
```suggestion
```

2020-03-20 15:34 UTC, jsmorgan42 commented on Vocable/Features/Settings/Views/SettingsFooterCollectionViewCell.swift
>          versionLabel.textColor = .defaultTextColor
Good suggestion, just pushed these changes

2020-03-20 15:39 UTC, jsmorgan42 commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +    private func regularHeightWidthLayout() -> UICollectionViewLayout {
I thought this was kind of a weird name since it's not just for regular heigh regular width but rather for landscape iPhone (Compact Height/Any Width) and iPad (Regular Height/Regular Width). Not sure what a good name would be for that

2020-03-20 20:31 UTC, jsmorgan42 commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let internalLinksItemCount = dataSource.snapshot().itemIdentifiers.count - 3
The best way to get rid of this is to separate the internal links & external links by section. This looks like it's more difficult than I thought it'd be. I'm gonna take a look at this over the weekend.

2020-03-23 02:38 UTC, jsmorgan42 commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let internalLinksItemCount = dataSource.snapshot().itemIdentifiers.count - 3
I now have a named property with a comment attached

2020-03-23 15:22 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
>          }
Not sure if this is a good idea or not, but maybe having a `var isDebugOnly: Bool` on `SettingsItem` that can allow you to have a single list that you filter by would be cleaner? Branches like this that require editing multiple lines to toggle a feature flag give me a small amount of anxiety

2020-03-23 15:22 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let internalLinksItemCount = dataSource.snapshot().itemIdentifiers.count - externalLinksItemCount
Nice

2020-03-23 15:29 UTC, Clstroud commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let isEvenNumOfItems = internalLinksItemCount % 2 == 0
Perhaps `let isEvenNumOfItems = internalLinksItemCount.isMultiple(of: 2)` would be clearer?

2020-03-23 15:30 UTC, Clstroud commented on Vocable/Features/Settings/Views/SettingsCollectionViewCell.swift
> +    }
```suggestion
```

2020-03-23 15:30 UTC, Clstroud commented on Vocable/Features/Settings/EditSayings/EditSayingsCollectionViewCell.swift
>          textLabel.textColor = .defaultTextColor
This lingering textColor assignment doesn't match the other deletions in this PR. Is it still needed?

2020-03-23 15:36 UTC, jsmorgan42 commented on Vocable/Features/Settings/EditSayings/EditSayingsCollectionViewCell.swift
>          textLabel.textColor = .defaultTextColor
Nice catch, deleted

2020-03-23 15:37 UTC, jsmorgan42 commented on Vocable/Features/Settings/SettingsCollectionViewController.swift
> +        let isEvenNumOfItems = internalLinksItemCount % 2 == 0
I like that, seems clearer to me

2020-03-23 18:20 UTC, Clstroud approved these changes
Good stuff! 💰

2020-03-23 18:25 UTC, merged