feature/edit-saved-toast
willowtreeapps/eyespeak-ios pull request #160
Opened 2020-03-23 22:05 UTC by thomasshealy

Added a toast like message which gets displayed when  a user saves an edit to an existing phrase.

<img width="831" alt="Screen Shot 2020-03-23 at 5 48 54 PM" src="https://user-images.githubusercontent.com/20056220/77367416-6941d000-6d30-11ea-8fbc-1bb2a6d773b6.png">
<img width="831" alt="Screen Shot 2020-03-23 at 5 48 54 PM" src="https://user-images.githubusercontent.com/20056220/77367568-d6556580-6d30-11ea-86e8-132ed14f9fa4.png">

2020-03-23 23:24 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +    }
Is there a way to make this use the existing mechanism by making what's in `develop` slightly more generic? I'm not sure we want to go down the path of having a separate xib for each potential instance of this toast, unless there's another aspect of this that I'm not seeing. It seems like we need some means to present a toast with configurable text and it would always be the same?

2020-03-24 13:58 UTC, thomasshealy commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +    }
Yeah, I'm thinking now that this could be an extension of UIView, I will look into it.

2020-03-24 18:57 UTC, Clstroud requested changes
Just a few more suggestions in the spirit of generalizing that view, but it's looking much better :)

2020-03-24 18:57 UTC, Clstroud commented on Vocable/Common/Views/PhraseSavedView.swift
> +
```suggestion
```

2020-03-24 18:57 UTC, Clstroud commented on Vocable/Common/Views/PhraseSavedView.swift
> +    @IBOutlet weak var alertLabel: UILabel!
Since this is an attribute of the view itself, we can probably get away with calling it a `titleLabel` and making it private. This would be akin to something like `UIButton` having a property called `buttonLabel`, which feels redundant.

2020-03-24 18:57 UTC, Clstroud commented on Vocable/Common/Views/PhraseSavedView.swift
> +    }
Can this be a `var text: String` with a `didSet`? So for callers it would just be e.g. `toastView.text = "Saved to My Sayings"`?

2020-03-24 18:57 UTC, Clstroud commented on Vocable/Common/Views/PhraseSavedView.swift
>  class PhraseSavedView: BorderedView {
Since this is no longer specific to saving phrases, can it be named something generic like `ToastView`?

2020-03-24 18:57 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +    }
Is this still relevant in the latest revision?

2020-03-24 18:57 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> -        NotificationCenter.default.addObserver(self, selector: #selector(phraseSaved), name: .phraseSaved, object: nil)
Nice

2020-03-24 18:57 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +             phraseSavedView.translatesAutoresizingMaskIntoConstraints = false
Can you `Control + I` this? Looks like the indentation is a bit off

2020-03-24 19:59 UTC, stevefosterwta commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +         let fadeInOutDuration: TimeInterval = 0.5
Are there an extra spaces here?

2020-03-24 20:05 UTC, thomasshealy commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +         let fadeInOutDuration: TimeInterval = 0.5
I don't think so.

2020-03-25 15:43 UTC, Clstroud commented on Vocable/Common/Views/ToastView.swift
>          super.awakeFromNib()
```suggestion
        super.awakeFromNib()
        titleLabel.text = text
```
Ensuring that if the xib is loaded lazily, the titleLabel will get some text if it was already assigned

2020-03-25 15:44 UTC, Clstroud commented on Vocable/Common/Views/ToastView.swift
> +            titleLabel.text = text
```suggestion
            titleLabel?.text = text
```
Like the `awakeFromNib`, this ensures that we won't crash in the event that the xib gets lazily loaded and the text is set before titleLabel becomes available. It's not likely in the current implementation, but this class doesn't have knowledge of that :)

2020-03-25 15:46 UTC, Clstroud approved these changes
Just two more inline suggestions, but LGTM 👍

2020-03-25 16:02 UTC, thomasshealy commented on Vocable/Common/Views/ToastView.swift
> +            titleLabel.text = text
Good call.

2020-03-25 16:08 UTC, merged