Language-specific word predictions and displaying only one "My Sayings" category
willowtreeapps/eyespeak-ios pull request #173
Opened 2020-03-28 21:57 UTC by pg8wood

Opening this draft to discuss localization strategy. This is an early working copy, and any suggestions for improvements are more than welcome! 

## Additions: 
- Always use the device locale for the `UITextChecker` predictions. This allows us to predict for any language supported by iOS, even if we haven't localized the preset phrases yet
- Adds a lightweight migration of the Core Data store to add a `locale` property to `Category` and `Phrase` data models
  - Expands the `AppDelegate`'s Core Data routines to give the `locale` a default value when migrating the Core Data store. This is required since we cannot hard-code a default value for the locale in the Core Data models
- Uses `locale` to prevent showing multiple "My Sayings" categories
- Ensures the `AVSpeechSynthesizer` speaks using the correct voice--English for untranslated preset phrases and the device locale's default voice for translated phrases and custom phrases from the keyboard and in "My Sayings"

<img src="https://user-images.githubusercontent.com/16855664/77834427-15adf880-711b-11ea-800d-240c2b14b5c2.PNG" height=50% width=50%/>

**Supported localization <translated "My Sayings"> category and localized text predictions**
https://imgur.com/a/qLHwSNy

**Unsupported localization "My Sayings" (non-localized) category and localized text predictions**
https://imgur.com/a/r1Ryunc

2020-03-30 15:02 UTC, Clstroud commented on Vocable/CoreData/NSManagedObject+Helpers.swift
> +    static func fetchAll(in context: NSManagedObjectContext, locale: String? = Locale.current.identifier, sortDescriptors: [NSSortDescriptor]? = nil) -> [Self] {
I don't think this makes sense as a change for all `NSManagedObject` since they aren't guaranteed to have a `locale` property. I would suggest maybe having an optional predicate parameter and then having a locale-aware variant of this function as an extension on `Phrase`/`Category` that specifies a locale via the predicate parameter in this function.

2020-03-30 15:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +        Category.fetchAll(in: context, locale: nil).forEach { category in
This function says it's migrating user-generated content but it's currently doing _everything_. I assume that's because we don't have locale-aware JSON yet?

2020-03-30 15:07 UTC, Clstroud commented on Vocable/Features/Presets/PresetPageCollectionViewController.swift
> +                if viewModel.categories.map({ $0.name }).contains(NSLocalizedString("My Sayings", comment: "Category: My Sayings")) {
Can we have a hardcoded identifier for My Sayings so we're not relying on these strings? If we change the name of the category this could break

2020-03-31 16:28 UTC, pg8wood commented on Vocable/AppDelegate.swift
> +        Category.fetchAll(in: context, locale: nil).forEach { category in
Re: our in-person conversation: I'll remove this and we can assume English as a default if the locale is nil

2020-04-02 17:04 UTC, Clstroud requested changes

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +        let context = container.newBackgroundContext()
We should chat about this -- right now the UI doesn't have a means of handling the "I'm migrating Core Data, give me a second." Thinking it might be better to block until we're ready to display data or have a strategy for migration limbo.

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +        let preferredLocals = Bundle.main.preferredLocalizations
Typo: "Locales"

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +        let preferredLocals = Bundle.main.preferredLocalizations
Also not sure how this compares to `Locale.preferredLanguages` but we should double check the docs to make sure we're using the right thing. @pg8wood might have some insight since he's been brushing up on that stuff more recently.

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +            phrase.creationDate = Date()
I believe this should check the `.isInserted` property to make sure it is, in fact, a newly created object.

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
>              category.creationDate = Date()
I believe this should check the `.isInserted` property to make sure it is, in fact, a newly created object.

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
>              }
Is this is going to have the right effect? I think you should be getting the first `preferredLocales` element that `presetCategory.localizedName.keys` contains, then use that to get your name string. You could possibly even do that as a `guard` before attempting to fetch/create the managed object.

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +                phrase.utterance = presetPhrase.localizedUtterance[locale]
Same question as above re: how this loop is working. Granted, this one has a `break` so it should have fewer side-effects, but it still looks to me like it would be grabbing the first preset `localizedUtterance` and getting the first `preferredLocale` element that matches its key... which would be the same value? I think?

2020-04-02 17:04 UTC, Clstroud commented on Vocable/AppConfig.swift
> +    static let preferredLanguageIdentifier = Locale.preferredLanguages.first ?? Locale.current.identifier
I don't think this is needed with the updated strategy? The new strategy is meant to allow us to respect the entire array of preferred languages as fallback values. Whether that's 100% the correct thing to do remains to be seen.

2020-04-02 19:48 UTC, stevefosterwta commented on Vocable/AppDelegate.swift
> +        let context = container.newBackgroundContext()
I don't think that saving changes from a background context to view context is a bottleneck.

2020-04-02 19:49 UTC, stevefosterwta commented on Vocable/AppDelegate.swift
> +        let context = container.newBackgroundContext()
That being said using the view context isn't that bad.

2020-04-03 19:42 UTC, jsmorgan42 approved these changes
🥇

2020-04-03 19:42 UTC, jsmorgan42 commented on Vocable/Features/Presets/PresetsPageViewController.swift
> +        if ItemSelection.selectedCategory.identifier == TextPresets.numPadIdentifier {
💯

2020-04-03 19:42 UTC, Clstroud approved these changes

2020-04-03 19:43 UTC, merged