Feature/window refactor
willowtreeapps/eyespeak-ios pull request #174
Opened 2020-03-30 01:41 UTC by thomasshealy

Refactored the Head Gaze Window so that it is no longer responsible for displaying notifications (head tracking lost, phrased saved, etc.).

2020-03-30 14:13 UTC, Clstroud requested changes
This is a solid first pass, but there are a handful of things that could use another cleanup pass and/or a little bit more elbow grease to more closely approximate what we discussed during planning. More than happy to chat about specifics 😄

2020-03-30 14:13 UTC, Clstroud commented on Vocable/AppDelegate.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(applicationDidAcquireGaze(_:)), name: .headTrackingDisabled, object: nil)
I almost commented that I thought it was sending a message to the wrong selector, but now I see why you're doing this. Can you make an additional function that handles this case to make it more explicit that we want to dismiss the warning in the event that head tracking is disabled? Maybe even adding a comment for clarity?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +class NotificationWindow: UIWindow {
`NotificationWindow ` -> `ToastWindow` for prefix consistency?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +        if NotificationWindow.passThroughTag == hitView?.tag {
What effect does this actually have/why is it needed? In which cases should the entire window _not_ return `nil` and/or have `.userInteractionEnabled = false`?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +    var toastContainer: ToastContainerViewController {
Suggestion: `toastContainer` -> `toastContainerViewController`, since "container" itself doesn't really imply any sort of conventional type in UIKit. Would probably improve readability for callers.

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +    private var cancellables = Set<AnyCancellable>()
This doesn't appear to be used?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +      //  handleWarning(shouldDisplay: false)
Is this function still relevant?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +      //  handleWarning(shouldDisplay: false)
Is this function still relevant?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
> +       // handleWarning(shouldDisplay: true)
Is this function still relevant?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +    }
Anything operating in Toast-land should have no concept of the content being displayed, only the kind of toast that's being presented. Things like "Phrase saved" or "Warning" are concepts that should be confined to the callers. Instead we should have concepts like we discussed in planning such as "ephemeral" or "persistent" with strings and images.

2020-03-30 14:13 UTC, Clstroud commented on Vocable/Features/Settings/EditSayings/EditKeyboardViewController.swift
> +    private var notificationWindow: NotificationWindow?
Is this instance used?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/Features/Presets/PresetsViewController.swift
> +    private var notificationWindow: NotificationWindow?
Is this instance used?

2020-03-30 14:13 UTC, Clstroud commented on Vocable/Common/ToastContainerViewController.swift
> +    private var warningViewVisible = false
I think these are redundant? The views themselves get `nil`'d out when they are dismissed

2020-03-30 14:13 UTC, Clstroud commented on Vocable/Common/ToastContainerViewController.swift
> +        NotificationWindow.shared.isHidden = false
In general the view controller should not be manipulating its parent's window like this. IMO this should be the job of the generic `ToastController` we discussed during planning.

2020-03-30 14:13 UTC, Clstroud commented on Vocable/Features/Presets/PresetsViewController.swift
> +                    NotificationWindow.shared.handlePhraseSaved(toastLabelText: NSLocalizedString("Saved to My Sayings", comment: "Saved to My Sayings"))
Another reason for the `ToastController`: it feels clunky for callers to make any assumptions about how Toasts are being presented. The window itself should be a hidden implementation detail.

2020-03-30 14:28 UTC, thomasshealy commented on Vocable/HeadGazeLib/NotificationWindow.swift
> +        if NotificationWindow.passThroughTag == hitView?.tag {
Good call, this is a much better way.

2020-03-30 15:22 UTC, thomasshealy commented on Vocable/Common/ToastContainerViewController.swift
> +    private var warningViewVisible = false
I need them to signal when their respective animations are done.  If I don't then the window can get set to hidden before a fade out of one of the warnings is complete - which is problematic.  I'm open to suggestions on other ways to do this, the other methods I tried led to some messy force unwraps.

2020-03-30 16:57 UTC, Clstroud commented on Vocable/Common/ToastContainerViewController.swift
> +    private var warningViewVisible = false
This sounds like it would lend itself to the notion of a completion handler in the toast model object (that would hypothetically be stored on the stack in the persistent case). That way the handler can be called when the animation completes and the hypothetical `ToastController` can decide what to do based on how many things are being still displayed/enqueued.

2020-03-31 15:03 UTC, Clstroud approved these changes

2020-03-31 15:03 UTC, Clstroud commented on Vocable/Common/ToastContainerViewController.swift
> +    func updateWindowVisibility() {
```suggestion
    private func updateWindowVisibility() {
```

2020-03-31 15:03 UTC, Clstroud commented on Vocable/Common/Views/WarningView.swift
>      override func awakeFromNib() {
This function isn't doing anything anymore and can be deleted

2020-03-31 15:03 UTC, Clstroud commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
>      override func addSubview(_ view: UIView) {
This probably isn't doing anything now that we've removed those excess views

2020-03-31 15:03 UTC, Clstroud commented on Vocable/Common/ToastContainerViewController.swift
> +        }
Per our pairing yesterday: since we know we aren't happy with this `ToastWindow.shared.isHidden` business and are running with it for the time being, can we add a comment saying that a future revision should move away from manipulating that window from here?

2020-03-31 16:05 UTC, thomasshealy commented on Vocable/HeadGazeLib/HeadGazeWindow.swift
>      override func addSubview(_ view: UIView) {
We still need this to bring the cursor view to the front.

2020-03-31 16:08 UTC, merged