Main screen test setup
willowtreeapps/eyespeak-ios pull request #272
Opened 2020-04-27 20:11 UTC by stechkev

quick and dirty setup of basic tests for the main screen of the app. Also added a new test helper class to hold the default setup and teardown methods, as well as screenshot functionality for failures.

Things to know are that there is a big refactor coming so a lot of the references will be overwritten or changed. As part of that we are going to introduce a bunch of accessibility ids so that we don't have to have crazy view heirarchy references all over the place.

2020-04-28 16:08 UTC, Clstroud commented on VocableUITests/Screens/MainScreen.swift
> +    let defaultPhraseBasicNeeds = ["I want to sit up", "I am finished", "I am uncomfortable", "I am fine", "I want to lie down", "I am in pain", "I am good", "I am tired"]
Is there a way we can leverage identifiers for categories rather than strings? Moreover: should we?

Any changes to the presets content will break UI tests.

2020-04-29 14:25 UTC, stechkev commented on VocableUITests/Screens/MainScreen.swift
> +    let defaultPhraseBasicNeeds = ["I want to sit up", "I am finished", "I am uncomfortable", "I am fine", "I want to lie down", "I am in pain", "I am good", "I am tired"]
Ideally, yes we should use identifiers in several places in this. right now, considering the refactor, i wanted to get things up and running. since a lot of things will break with the refactor anyway, I think that's a good time to add in identifiers and fix the tests.

2020-04-30 19:34 UTC, nerdsosky approved these changes
Nice, this is a good starting point. Just one minor thing to fix

2020-04-30 19:34 UTC, nerdsosky commented on VocableUITests/Tests/TestHelper.swift
> +class TestHelper: XCTestCase {
Should go ahead and rename this to BaseTest so it's clear what this is going to be based on our discussion yesterday

2020-04-30 23:34 UTC, nerdsosky commented on VocableUITests/Tests/MainScreenTests.swift
> +class MainScreenTests: BaseScreen {
Test classes should have their own BaseTest instead of BaseScreen

2020-04-30 23:35 UTC, nerdsosky commented on VocableUITests/Tests/BaseScreen.swift
> +class BaseScreen: XCTestCase {
BaseScreen doesn't need to inherit from anything it can be it's own class. The setup functions should go in the BaseTest class

2020-05-01 00:00 UTC, nerdsosky requested changes
Added some more comments

2020-05-01 15:34 UTC, nerdsosky approved these changes

2020-05-01 15:38 UTC, merged