Add Recents category
willowtreeapps/eyespeak-ios pull request #406
Opened 2020-10-12 17:41 UTC by CarolineLaw

https://github.com/willowtreeapps/vocable-ios/issues/359

closes 359

# Description of Work
Added recents category, also added localized strings

## Notes to Test (Optional)
Naming things is hard, lemme know if you have any suggestions (is bodyLabel okay?? idk????) Also I wanna talk about refactoring the EmptyStateView so that we check for if things are nil before putting it in the stack view ty!!!!!

---

2020-10-12 18:01 UTC, SpudLaw commented on Vocable/Common/Views/EmptyStateView.swift
> +        self.bodyAttributedText = nil
this works, but it's not great pls help meee

2020-10-12 18:01 UTC, CarolineLaw commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +            request.fetchLimit = 9
also we should talk about this and how the fetchLimit should probably be something else :x

2020-10-12 18:46 UTC, Clstroud requested changes
A handful of small requests, but nothing huge. Overall this is looking great, @CarolineLaw  😄

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
If this and the other snippet that does the same for the image were moved into a function, you could call that function from `commonInit()` and from their respective `didSet`s, which would avoid the need to trigger this side effect by redundantly setting those properties to `nil` in the initializers.

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Common/Views/EmptyStateView.swift
> +    var bodyAttributedText: NSAttributedString? {
If this is named `bodyAttributedText` it might make sense to rename `attributedText` to `headerAttributedText` to maintain that level of specificity and clarity. Same for the other properties, actually.

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Common/Views/EmptyStateView.swift
> +    init(attributedText: NSAttributedString, image: UIImage? = nil, extraAttributedText: NSAttributedString? = nil, action: ButtonConfiguration? = nil) {
`attributedText`/`extraAttributedText` naming should stay consistent with the header/body concepts you've introduced elsewhere here

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +            request.fetchLimit = 9
I'm not sure we're going to find a better solution than just picking a number and sticking to it. If the device rotates and the number of items on screen changes, we wouldn't want to artificially take items away from the user that were _just_ visible before the rotation.

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +        try! frc.managedObjectContext.save()
This save should only fire if you assign a new `lastSpokenDate`. You should also make it a `try?` just in case.

2020-10-12 18:46 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"recents_empty_state.body.title" = "Start using your app to see your most recently used phrases here.";
Vocable referring to itself as "your app" does not feel right one bit

2020-10-12 19:54 UTC, CarolineLaw commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
I talked to Ameir and he said we should use a designated initializer here, I think I might go for that. Sound good?

2020-10-12 20:25 UTC, Clstroud commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
I would be on board with that if those properties weren't externally assignable? I'm not _personally_ a huge fan of requiring everything to be crammed into an initializer, but that's not a hill I'm planning to die on today

2020-10-12 21:00 UTC, CarolineLaw commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
@ameirwillowtree 👀

2020-10-12 21:27 UTC, ameirwillowtree commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
I would definitely advocate for a change to the size/number of initializers right now and try to simplify what "this thing can be". Perhaps an enum with associated values would be a nice way to require values for the distinct ways this thing can be created.

2020-10-12 21:28 UTC, ameirwillowtree commented on Vocable/Common/Views/EmptyStateView.swift
> +            }
A big factor is going to be how it looks/works at the call site which I'm not familiar with. So maybe look at those and see what feels right.

2020-10-20 20:44 UTC, pg8wood reviewed
Getting close! Looks super solid and I think will be ready with the `EmptyStateView` changes. Nice work! 💯

2020-10-20 20:44 UTC, pg8wood commented on Vocable/Common/Views/ToastView.xib
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="16097" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES
We can probably remove changes that just update the toolsVersion

2020-10-20 20:44 UTC, pg8wood commented on Vocable/Common/Views/EmptyStateView.swift
> +         image: UIImage? = nil, action: ButtonConfiguration? = nil) {
+1 for enumerating the types of `EmptyStateView` we can represent and simplifying this initializer. By doing that we can remove the subclasses and some of the technically impossible states this initializer can represent :+1:

2020-10-20 20:44 UTC, pg8wood commented on VocableUITests/Tests/CustomCategoriesTests.swift
> +        let createdCustomCategory = ("9. "+customCategory)
Talked in person about fixing this in the future 💯

2020-10-22 17:53 UTC, CarolineLaw commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +            let buttonTitle = NSLocalizedString("empty_state.button.title", comment: "Empty state Add Phrase button title")
i feel like we could make this better

2020-10-23 18:34 UTC, Clstroud approved these changes
LGTM 🎉 💯

2020-10-23 21:56 UTC, pg8wood approved these changes
![dancingPotatoes](https://user-images.githubusercontent.com/16855664/97057346-01b76180-1559-11eb-9660-a30fe3936945.gif)

2020-10-23 21:56 UTC, pg8wood commented on Vocable/Common/Views/EmptyStateView.swift
> +    var titleAttributedText: NSAttributedString? {
We probably no longer need to expose these if they're not being used outside this type, otherwise someone could come in and change our `titleLabel` or `descriptionLabel` text out from under us. Unless I missed something and this is intentional!

Not a big deal though and no reason to hold up this PR any further

2020-10-26 18:38 UTC, merged