Added Recent Screen Test
willowtreeapps/eyespeak-ios pull request #451
Opened 2021-09-08 15:06 UTC by zachwhite99

Added test to verify that pressed buttons would show up in "Recents" category
---

2021-09-08 15:18 UTC, stechkev requested changes
found a couple things to change but overall logic looks really good!

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Screens/MainScreen.swift
> +    func scrollRightAndTapCurrentCategory(numTimesToScroll: Int, currentCategory: String) {
we refer to current category twice here but they reference different things. we should update either the name of the method or the variable to better capture the behavior

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Screens/MainScreen.swift
> +        // let currentCategory = numTimesToScroll % defaultCategories.count
should delete unused code unless it was left for a particular reason

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Screens/MainScreen.swift
> +        // FIXED: changed +1 to +numTimesToScroll
same with this comment

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Tests/MainScreenTests.swift
> +            */
i would move this to right above the test name

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Tests/MainScreenTests.swift
> +            buttonText = app.collectionViews.staticTexts.element(boundBy: 0).label // first button's label
get rid of comment and rename variable to firstButtonText

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Tests/MainScreenTests.swift
> +            listOfPressedButtons.append(buttonText) // add that button's text to listOfPressedButtons
probs don't need the comments here either

2021-09-08 15:18 UTC, stechkev commented on VocableUITests/Tests/MainScreenTests.swift
> +        for text in listOfPressedButtons {
text can be something a bit more descriptive

2021-09-08 15:57 UTC, zachwhite99 commented on VocableUITests/Screens/MainScreen.swift
> +    func scrollRightAndTapCurrentCategory(numTimesToScroll: Int, currentCategory: String) {
changed parameter name to "startingCategory"

2021-09-08 15:57 UTC, zachwhite99 commented on VocableUITests/Screens/MainScreen.swift
> +        // let currentCategory = numTimesToScroll % defaultCategories.count
deleted!

2021-09-08 15:57 UTC, zachwhite99 commented on VocableUITests/Screens/MainScreen.swift
> +        // FIXED: changed +1 to +numTimesToScroll
deleted!

2021-09-08 15:57 UTC, zachwhite99 commented on VocableUITests/Tests/MainScreenTests.swift
> +            */
moved to above test name

2021-09-08 15:58 UTC, zachwhite99 commented on VocableUITests/Tests/MainScreenTests.swift
> +            buttonText = app.collectionViews.staticTexts.element(boundBy: 0).label // first button's label
renamed variable to "firstButtonText"

2021-09-08 15:58 UTC, zachwhite99 commented on VocableUITests/Tests/MainScreenTests.swift
> +            listOfPressedButtons.append(buttonText) // add that button's text to listOfPressedButtons
removed comments here

2021-09-08 15:59 UTC, zachwhite99 commented on VocableUITests/Tests/MainScreenTests.swift
> +        for text in listOfPressedButtons {
changed "text" variable name to "pressedButtonText"

2021-09-09 19:04 UTC, stechkev approved these changes
looks good!

2021-09-09 19:12 UTC, merged