#465 Allow categories and phrases to be universally editable
willowtreeapps/eyespeak-ios pull request #471
Opened 2022-03-15 15:17 UTC by Clstroud

Closes #465

# Description of Work

### Functionally
If the category or phrase is a preset, it can be renamed and deleted just like their user-defined counterparts
- Renaming means marking them as "user-renamed" so that subsequent updates of the presets don't overwrite the user's entry
- During "deletion" the category or phrase is marked as "user-removed" so that subsequent updates to the presets don't recreate the removed entity. We simply suppress it from showing in the UI at all.
- User-generated categories and phrases are still permanently deleted because there is no consequence for that

### Code changes
- I felt that the way Core Data predicates were being handled was getting a bit terse, so I made some lightweight global functions and operators to make dealing with them more readable and concise. I steered away from making anything too fancy (I hope), so hopefully these strike a nice balance.

## Notes to Test 
- This does not change the UI from previous builds beyond enabling/disabling buttons
- The "My Sayings" category is still a special case that is not deletable 
- We should do some testing to ensure we upgrade gracefully from the App Store version of the app
   - Specifically the "My Sayings" category migration

2022-03-15 22:56 UTC, moyerr commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Using global functions with capitalized names really provides the ergonomics of dealing with a more concise and type-safe wrapper type, but without the burden of bridging with all the CoreData APIs. I like it! 

I don't think I've seen this pattern before; was there a particular inspiration to go this direction here? If I was doing the same thing, I probably would've reached for a `typealias` with a series of convenience initializers. I don't think one is necessarily better than the other, I'm just curious what led to this particular design choice 🙂

2022-03-16 12:57 UTC, Clstroud commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Thanks! Glad it's as intuitive as I'd hoped it might be 🙂 You're spot-on about the goal of the ergonomics.

As for inspiration: I wasn't modeling it off of anything in particular. I kicked around a couple ideas that didn't quite feel right and eventually landed here. Part of the influence was the [existing code](https://github.com/willowtreeapps/vocable-ios/blob/74fe115b62e81dadbaf96e92c88654846ec87881/Vocable/CoreData/NSManagedObject%2BHelpers.swift#L52) that wasn't really cutting it.

I think having a `typealias Predicate` would be a sensible starting point for sure, but you'd still be confined to a particular class of `NSPredicate` and unable to choose which subclass you want to vend. I believe all of these are vending an `NSComparisonPredicate`, but I can imagine a few additional functions we could add that might want to switch it up and vend an `NSCompoundPredicate` instead. Can't really do that with a custom initializer.

Moreover, the convenience logical operators I added inherently work more or less the same way, so there's something to be said about the consistency of `-> NSPredicate`.

Almost like everything is returning an `any Predicate` without the existential dread 🥁

2022-03-16 13:02 UTC, Clstroud commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Other thoughts for future tinkering:
1. If we really wanted to get crazy, we could introduce operators that could make e.g. `Predicate(\Category.isUserGenerated == false)` valid
2. Potential ergonomic improvements by making these an extension on `NSManagedObject` e.g. `Category.Predicate(\.isUserGenerated == false)` but that feels a little more subjective ¯\_(ツ)_/¯

2022-03-16 14:12 UTC, jsmorgan42 commented on Vocable/AppDelegate.swift
> +            return isUserGenerated && identifierNotPrefixed
Definitely a fan of these changes, makes it much easier to reason what's happening here 👏

2022-03-16 14:31 UTC, jsmorgan42 commented on Vocable/AppDelegate.swift
> -    }
Why was this removed?

2022-03-16 14:43 UTC, jsmorgan42 commented on Vocable/CoreData/Phrases.xcdatamodeld/Phrases v4.xcdatamodel/contents
> +        <attribute name="creationDate" optional="YES" attributeType="Date" usesScalarValueType="NO"/>
Was curious why the creation date for a phrase is optional?

2022-03-16 14:45 UTC, SashankPatel commented
Verified Phrases can now be removed from preset categories and empty state appears.

ISSUE: Preset Categories can not be removed. Custom Categories can be removed.

2022-03-16 15:07 UTC, jsmorgan42 commented on Vocable/Extensions/PredicateBuilders.swift
> +}
@Clstroud I like the first potential improvement a lot even though it might be slightly overkill. It feels like that would make things even more readable.

2022-03-16 15:11 UTC, jsmorgan42 commented on Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
> +            return true
Can we just combine this into one case with `.titleEditView` on line 225 since they both return true?

2022-03-16 15:15 UTC, jsmorgan42 commented on Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
> +        }
This can definitely be cleared up in another piece of work, but I wonder if we should show some kind of error alert if the category fails to get removed?

2022-03-16 15:19 UTC, jsmorgan42 commented on Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
> +
Extra space

2022-03-16 20:09 UTC, Clstroud commented on Vocable/AppDelegate.swift
> -    }
Yep! We may need to bring this back in _some_ form once we test the App Store upgrade path, but to the very best of my knowledge this was just to handle upgrades from earlier iterations of the feature that were never released.

2022-03-16 20:12 UTC, Clstroud commented on Vocable/CoreData/Phrases.xcdatamodeld/Phrases v4.xcdatamodel/contents
> +        <attribute name="creationDate" optional="YES" attributeType="Date" usesScalarValueType="NO"/>
"Optional" in the context of Core Data is more about validation requirements when saving objects than what I assume you're probably think of (Swift.Optional). It's just marked optional here because that's the default in the editor, but it doesn't have much bearing on how we're using it

2022-03-16 20:15 UTC, Clstroud commented on Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
> +
If you wouldn't mind using the PR suggestions feature for this in the future, that'd be great 💯 

But yes, I'll take care of it.

2022-03-16 20:20 UTC, Clstroud commented on Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
> +        }
Yeah, I mostly shifted it this way to ensure we couldn't just lose the user's entry when there's a failure, but for the moment I'm reasonably confident this will be fine. Having more robust error handling for these edits could be its own ticket honestly.

2022-03-16 22:18 UTC, Clstroud commented
Thanks to @rowildcard for finding the issue where preset category deletions were not being reflected by the UI! 

It led to a handful of other observations which I just pushed fixes for:

* Ensure synthesized categories can't have phrases edited (Numpad, Recents, Listening Mode)
* Ensure the initially-selected category on the main screen is not one that has been removed by the user
* Ensure that the reordering controls on the Settings -> Edit Categories screen were updated properly after a category is deleted (some were being disabled erroneously)

2022-03-17 12:06 UTC, SashankPatel requested changes
Issue 1: App crashes when "Star'ing" a phrase from the keyboard i.e. tapping the favorite button
![Screen Shot 2022-03-17 at 8 05 08 AM](https://user-images.githubusercontent.com/50410188/158805032-cf6b00c5-256d-410d-a8c2-e731b6c788ae.png)
.


Issue 2: this is pretty minor: 
1.) Launch the app fresh so you have all the categories and the General Category should be visible.
2.) Navigate to Setting and delete the General Category. -> Basic Needs is now 1st in the list.
3.) Navigate back to main screen 
Expected: Basic needs to be visible.
Actual: Personal Care was visible.

2022-03-17 18:04 UTC, moyerr commented on Vocable/AppDelegate.swift
> +            return isNotUserGenerated && identifierNotInSet
I wonder if we could give this Predicate a little more semantic meaning as it relates to the fetchRequest? If I'm understanding the set of identifiers correctly, maybe something like `identifierDoesNotMatchPreset`? Or if that's too verbose, maybe do the negation on the following line: `return isNotUserGenerated && !identifierMatchesPreset`

2022-03-17 18:04 UTC, moyerr commented on Vocable/AppDelegate.swift
>              let identifiers = Set(presets.categories.map { $0.id })
You updated the closure to a keypath above. Could we do the same here?

```suggestion
            let identifiers = Set(presets.categories.map(\.id))
```

2022-03-17 18:04 UTC, moyerr commented on Vocable/Extensions/NSPredicate+Operators.swift
> +    }
Do these need to be `public`?

2022-03-17 18:04 UTC, moyerr commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Is it necessary to have an overload specifically for Optionals? Would these types not be covered by the more general version?

2022-03-17 18:04 UTC, moyerr commented on Vocable/Extensions/PredicateBuilders.swift
> +}
I love the way the `Predicate(_:equalTo:)` and `Predicate(_:notEqualTo:)` functions really provide that ✨ _clarity at the point of use_ ✨. Do you think it's worth it to provide something similar for collection-specific operators so we can keep the `PredicateOperator` as an implementation detail? Something like:
- `Predicate(_:beginsWith:)`
- `Predicate(_:endsWith:)`
- `Predicate(_:isIn:)`

2022-03-17 18:10 UTC, moyerr commented on Vocable/Features/Root/RootEditTextViewController.swift
> -        button.addTarget(self, action: #selector(favoriteButtonSelected), for: .primaryActionTriggered)
I think adding the target in `viewDidLoad` is perfectly valid, but an alternate approach I've used in the past is to make the view a `lazy var`. It's actually the [SwiftLint suggestion for this common mistake](https://realm.github.io/SwiftLint/self_in_property_initialization.html).

2022-03-17 18:26 UTC, rowildcard commented
Test verified. See issue for test details.

2022-03-17 18:34 UTC, rhsalas3 commented
> Test verified. See issue for test details.

Can confirm: I tested and verified the expected behavior as well, including adding phrases to 'My Sayings' from the keyboard screen. 

These changes look good to me.

2022-03-17 20:35 UTC, Clstroud commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Yeah, this is a weird thing that I'm _pretty_ sure is necessary (but I could be proven wrong). Reason is: some values we treat as non-optional but in Core Data land just about everything is technically nullable and the interfaces of the NSManagedObjects reflect that. Basically we need this optionality for pattern-matching to succeed in some cases but I don't have an example immediately available. I could be misremembering exactly why this was necessary, or we may be able to express it differently, but that's what I've got as an answer at the moment 😅 

Always happy to yeet some unnecessary code if we find it's extraneous... but for the moment I'd like to get this sucker merged so we can keep rolling.

2022-03-17 20:43 UTC, Clstroud commented on Vocable/Features/Root/RootEditTextViewController.swift
> -        button.addTarget(self, action: #selector(favoriteButtonSelected), for: .primaryActionTriggered)
I have done that in plenty of situations as well, but this time I talked myself out of it. There's just something about the way `lazy` changes the meaning of `self` that strikes me as unintuitive for newer developers that pushed me to move it to `viewDidLoad()`, you know? Give me 24 hours and I'm sure I can be persuaded back in the other direction 😛

2022-03-17 21:02 UTC, Clstroud commented on Vocable/Extensions/PredicateBuilders.swift
> +}
I will add just as many as are needed to make `PredicateOperator` a private implementation detail. And then that's all! 😉

2022-03-17 21:46 UTC, moyerr commented on Vocable/Extensions/PredicateBuilders.swift
> +}
Yeah, I haven't dealt with `NSExpressions` or `NSPredicates` too much so I don't have enough context to know for sure. I'm good with it as-is though!

2022-03-17 21:47 UTC, moyerr commented on Vocable/Features/Root/RootEditTextViewController.swift
> -        button.addTarget(self, action: #selector(favoriteButtonSelected), for: .primaryActionTriggered)
No change needed! I'm good either way 💯

2022-03-17 21:50 UTC, moyerr approved these changes
Huge fan of the documentation comments and the descriptive commits that reference the issue! 🏆

2022-03-17 21:57 UTC, merged