#477 | Fixing category selection after deletion
willowtreeapps/eyespeak-ios pull request #557
Opened 2022-04-11 19:54 UTC by jsmorgan42

closes #477

# Description of Work
Fixing a bug where after deleting the first category and navigating back to the home screen, the second category was selected inside of the first.

---

2022-04-12 15:08 UTC, moyerr approved these changes

2022-04-12 16:37 UTC, Clstroud requested changes
Just one question I'd like to make sure is a non-issue before I unblock this thing. Otherwise, nice and simple fix 💯

2022-04-12 16:37 UTC, Clstroud commented on Vocable/Features/Root/CategoriesCarouselViewController.swift
> +                }
I've been staring at this for a hot minute and I'm wondering if I'm misunderstanding something. `previous.indexPath` is no longer relevant to the new snapshot and could even be (I suppose?) out of bounds for said new snapshot, right?

What happens if you return `nil` instead?

2022-04-12 17:44 UTC, rowildcard commented
Test verified on:
simulator iPhone 8 Plus, iOS 15.4
iPhone 12 Pro Max, iOS 15.1

2022-04-13 19:24 UTC, Clstroud approved these changes
💯 Much safer. Good stuff 🥇

2022-04-13 20:16 UTC, CananArikan commented
Test verified on:
simulator iPhone 8, iOS 15.4
iPad Pro (11-inch) (3rd generation) 15.3.1

2022-04-13 22:19 UTC, merged