[567] Phrase selection repetition bug fix
willowtreeapps/eyespeak-ios pull request #568
Opened 2022-04-15 13:44 UTC by Clstroud

Closes #567 

# Description of Work
* Fixes the underlying issue causing the repetition
* Makes some heavily used UI elements update lazily to reduce overhead
* Moves infinite scrolling datasource preparation to a background queue for smoother updates

2022-04-15 15:08 UTC, jsmorgan42 commented on Vocable/Features/Root/CategoriesCarouselViewController.swift
> +    private var dataSourceProxy: DataSource!
Could we not instead just make this a private let that's instantiated on initialization of the view controller?

2022-04-15 15:11 UTC, jsmorgan42 commented on Vocable/Common/CarouselCollectionViewDataSourceProxy.swift
> +    private typealias Impl = UICollectionViewDiffableDataSource<ContentWrapper<SectionIdentifier>, ContentWrapper<ItemIdentifier>>
I know this was a pre-existing variable name but I wasn't sure what `Impl` is supposed to mean in this context 🤔

2022-04-15 15:36 UTC, jsmorgan42 commented on Vocable/Common/CarouselCollectionViewDataSourceProxy.swift
> +    private typealias Impl = UICollectionViewDiffableDataSource<ContentWrapper<SectionIdentifier>, ContentWrapper<ItemIdentifier>>
Maybe change to `Datasource`

2022-04-15 17:31 UTC, jsmorgan42 approved these changes
💯 💰 🚢

2022-04-15 17:39 UTC, jsmorgan42 requested changes
Looks like once you start switching between categories, the phrases are not displayed anymore, instead it only shows a blank screen
<img src=https://user-images.githubusercontent.com/37670742/163602984-54f0d2de-7597-4c1f-be2b-5932cf051566.png width=250>

2022-04-15 18:57 UTC, jsmorgan42 approved these changes

2022-04-21 14:36 UTC, rowildcard commented
Test verified on iPhone X, iOS 14.2
Verified:
Selecting preset phrases in each category. ✅ 
Selecting preset phrases on second page of a category. ✅ 
Add custom category and phrase; select custom phrase. ✅

2022-04-21 14:40 UTC, merged