[573] Hover Time tests
willowtreeapps/eyespeak-ios pull request #576
Opened 2022-04-18 20:43 UTC by rowildcard

https://github.com/willowtreeapps/vocable-ios/issues/573

# Description of Work
This automation test verifies the UI controls for Hover Time in Settings. 

- User can decrease hover time
- User can increase hover time
- User selected hover time persists after leaving and returning to Settings

2022-04-18 21:30 UTC, rowildcard commented on VocableUITests/Tests/BaseTest.swift
> +    let app = XCUIApplication()
I moved the declaration of the `app` instance outside of the `setUp()` function so it's visible by all the tests.

2022-04-20 19:17 UTC, Clstroud requested changes
Mostly just Swift-isms and I think this needs to heartbeat the latest changes from #564, but nice first PR 💯 🏆 

Happy to chat through any questions 😄

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/SettingsScreen.swift
> +        timingAndSensitivityButton.tap()
```suggestion
        MainScreen.settingsButton.tap(afterWaitingForExistenceWithTimeout: 2)
        timingAndSensitivityButton.tap(afterWaitingForExistenceWithTimeout: 2)
```
I would double check this before committing, but I believe Rudy's latest changes allow for this ^

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/SettingsScreen.swift
>      let keyboardScreen = KeyboardScreen()
I believe this goes away with Rudy's latest changes, since you should now be able to refer to KeyboardScreen statically instead of carrying an instance around

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/SettingsScreen.swift
>      let settingsPageNextButton = XCUIApplication().buttons["bottomPagination.right_chevron"]
```suggestion
    static let categoriesButton = XCUIApplication().collectionViews.staticTexts["Categories and Phrases"]
    static let timingAndSensitivityButton = XCUIApplication().collectionViews.staticTexts["Timing and Sensitivity"]
    static let otherElements = XCUIApplication().collectionViews.cells.otherElements
    static let cells = XCUIApplication().cells
    static let settingsPageNextButton = XCUIApplication().buttons["bottomPagination.right_chevron"]
```
I believe all of these can be static with Rudy's latest, which should be a nice ergonomic improvement. Same goes for the functions below 😄

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/TimingAndSensitivityScreen.swift
> +    var maximumHoverTime = "5.0s"
Same here regarding static members

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/TimingAndSensitivityScreen.swift
> +    var defaultHoverTime = "1.0s"
This default value is read-only, so I think it can be a `let` instead of a `var`? `min` and `max` values a few lines down would also be read-only I believe.

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/TimingAndSensitivityScreen.swift
> +    }
```suggestion
```
I think we can move this up into the default values for each of these. Might take a tiny bit of finagling to make it work once they're static, but it won't be bad.

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Screens/TimingAndSensitivityScreen.swift
> +    }
```suggestion
    func hasMinimumHoverTimeBeenReached() -> Bool {
        currentHoverTimeIndex == rangeOfHoverTimes.indices.first
    }
    
    func hasMaximumHoverTimeBeenReached() -> Bool {
        currentHoverTimeIndex == rangeOfHoverTimes.indices.last
    }
```
Perhaps these are a little more expressive about the intent here? What you have is fine if you prefer it 😄

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Tests/CustomPhraseTests.swift
> +        _ = phraseQuery.element.waitForExistence(timeout: 2)
Would it be appropriate to fail here in the event that the element doesn't come into existence? Figuring out what happened downstream might be a little less clear

2022-04-20 19:17 UTC, Clstroud commented on VocableUITests/Tests/TimingAndSensitivityTests.swift
> +        XCTAssertTrue(!timingScreen.hoverTimeIncreaseButton.isEnabled)
```suggestion
        XCTAssertFalse(timingScreen.hoverTimeIncreaseButton.isEnabled)
```
Same could apply up above 😄

2022-04-21 17:17 UTC, rowildcard commented
I'm submitting a new PR for the hover timing test. There were just too many changes when pagination was merged to have confidence in resolving all the conflicts.

2022-04-21 17:17 UTC, closed without merging