[Automation] #570 | Add Preset Phrase Tests
willowtreeapps/eyespeak-ios pull request #595
Opened 2022-04-22 19:36 UTC by CananArikan

closes #570 

# Description of Work
`PresetPhraseTests` class created and new tests are added to test these scenarios:

- `testAddNewPhrase()`
- `testEditPresetPhrase()`
- `testDeletePresetPhrase()`
- `testEditPhrasesButtonIsDisabledForNumberPadCategory()`
- `testEditPhrasesButtonIsDisabledForRecentsCategory()`
- `testAddDuplicatePhrasesToMySayings()`

## Notes to Test (Optional)
`PresetPhraseTests` test suite should pass on an iPhone and iPad

2022-04-22 20:11 UTC, rhsalas3 commented
Ran the tests locally and they all passed! 🎉

2022-04-22 21:21 UTC, rhsalas3 commented on VocableUITests/Screens/BaseScreen.swift
>  }
This is the 3rd function doing the same loop now, so I think this is a good candidate for refactor. I don't think we need to hold up this PR now for it, we can just add this to our list of what to consolidate and refactor in #562

2022-04-25 14:41 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        KeyboardScreen.checkmarkAddButton.tap()
It's not necessary, but we have a helper function for this already. We could reduce the number of lines here from 3 to 1. It's the CustomCategoriesScreen `addPhrase(_ phrase: String)` function.

No need to change anything for this unless you have to update something else 😉

2022-04-25 14:49 UTC, rowildcard approved these changes

2022-04-25 14:49 UTC, rowildcard commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        // Verify that phrase doesn't exist in Category Details Screen
Should this comment say, "Verify that phrase **does** exist..."?

2022-04-25 14:49 UTC, rowildcard commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        // Verify that phrase doesn't exist in Main Screen
Should this comment say, "Verify that phrase does exist..."?

2022-04-25 14:49 UTC, rowildcard commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        XCTAssertEqual(phraseQuery.count, 2, "Expected both phrases to be presentin 'My Sayings'")
A typo in your message: "... to be presen**t i**n ..."

2022-04-25 15:24 UTC, rhsalas3 requested changes
I think overall this is good. I left some comments for some minor changes though. But these tests will be a good addition! 🙂

2022-04-25 15:24 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        firstPhraseCell.tap()
It would be more precise, and leaves less room for potential issues, if we tap the specific button for the phrase (vs the delete button) by specifying which element within the cell we want to tap. Maybe something like: `firstPhraseCell.staticTexts[firstPhrase].tap()`.

2022-04-25 15:24 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let firstPhrase = firstPhraseCell.staticTexts.firstMatch.label
I think it may be helpful to lessen any possible confusion about what's going on in this test by renaming your variables. 

I'm thinking `firstPhraseId` (and its subsequent variables) can change to `originalPhraseId`. 

Then before line 57 we can declare a new variable to represent our updated phrase, to be used in line 57:
```
let updatedPhrase = originalPhrase + customPhrase
XCTAssertTrue(CustomCategoriesScreen.doesPhraseExist(updatedPhrase))
```

2022-04-25 15:24 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        XCTAssertFalse(MainScreen.doesPhraseExist(firstPhrase))
I think we should remove this line. We can be pretty confident that if the phrase was not present when we checked for it from the edit phrases screen it won't be there on the Main screen. So we can save some time here, by removing this line.

2022-04-25 15:24 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        KeyboardScreen.createDuplicateButton.tap()
Because we're waiting for the alert to appear, we should play it safe here and wait for the button before tapping. Using `KeyboardScreen. createDuplicateButton.tap(afterWaitingForExistenceWithTimeout: 0.25)`.

2022-04-25 17:17 UTC, rhsalas3 commented
I have run all of the tests 3 times:
 1. Locally using Xcode
 2. Locally using `fastlane ios test`
 3. Remotely from CircleCI 

The new tests, and all of the others, ran and passed each time. 💵  💰 💸

2022-04-25 18:41 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        KeyboardScreen.checkmarkAddButton.tap()
Implemented!

2022-04-25 19:27 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let firstPhrase = firstPhraseCell.staticTexts.firstMatch.label
Thanks, renamed!

2022-04-25 19:27 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        XCTAssertFalse(MainScreen.doesPhraseExist(firstPhrase))
Removed.

2022-04-25 19:28 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        firstPhraseCell.tap()
Implemented!

2022-04-25 19:28 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        KeyboardScreen.createDuplicateButton.tap()
Updated!

2022-04-25 20:59 UTC, rhsalas3 requested changes
Thank you for incorporating the feedback from earlier. 

There are a few new typos and areas for small changes, that relate to your updates from the previous feedback. 

I made each comment a Github `Suggestion` so that, if you wanted to, you could commit the change from within the comment dialog box on this PR instead of switching back over to XCode etc.

2022-04-25 20:59 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        // Verify that phrase doesn exist in Main Screen
```suggestion
        // Verify that phrase does exist in Main Screen
```

2022-04-25 20:59 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        //firstPhraseCell.tap()
Can delete this comment now:
```suggestion

```

2022-04-25 20:59 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        XCTAssertTrue(CustomCategoriesScreen.doesPhraseExist(updatedPhrase))
We should create our `updatedPhrase` variable right before its use. It also makes sense to update the comments.

```suggestion
        // Verify that the original phrase doesn't exist in Category Details Screen
        XCTAssertFalse(CustomCategoriesScreen.doesPhraseExist(originalPhrase))
        
        // Verify that updated phrase exists in Category Details Screen
        let updatedPhrase = originalPhrase + customPhrase
        XCTAssertTrue(CustomCategoriesScreen.doesPhraseExist(updatedPhrase))
```

2022-04-25 20:59 UTC, rhsalas3 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        XCTAssertTrue(MainScreen.doesPhraseExist(updatedPhrase))
Since we are no longer checking that the original phrase appears on the main screen, we can remove the extra comment and consolidate the code block, like this:
```suggestion
        // Verify that updated phrase exists in Main Screen
        CustomCategoriesScreen.returnToMainScreenFromEditPhrases()
        MainScreen.locateAndSelectDestinationCategory(.personalCare)
        XCTAssertTrue(MainScreen.doesPhraseExist(updatedPhrase))
```

2022-04-26 14:43 UTC, Clstroud commented on Vocable/Common/AddPhraseCollectionViewCell.swift
> +        textLabel.accessibilityIdentifier = "mainScreen.addPhrase"
It may make sense to have this be set in ~`CategoryDetailViewController:116` since the cell doesn't necessarily know that it's being shown on the main screen. Alternatively, just having it just be something like `add_new_phrase` might make it contextually agnostic and be fine to keep here.

2022-04-26 14:43 UTC, Clstroud commented on VocableUITests/Tests/PresetPhraseTests.swift
> +            XCTAssertFalse(CustomCategoriesScreen.editCategoryPhrasesButton.isEnabled)
```suggestion
        let categoryName = "123"
           
        SettingsScreen.navigateToSettingsCategoryScreen()
        SettingsScreen.openCategorySettings(category: categoryName)
        XCTAssertFalse(CustomCategoriesScreen.editCategoryPhrasesButton.isEnabled)
```

2022-04-26 14:48 UTC, jsmorgan42 commented on VocableUITests/Screens/BaseScreen.swift
> +        var flag = false
I think this variable name could be a bit more descriptive, maybe something like `phraseDoesExist`

2022-04-26 15:06 UTC, CananArikan commented on Vocable/Common/AddPhraseCollectionViewCell.swift
> +        textLabel.accessibilityIdentifier = "mainScreen.addPhrase"
Thanks! Implemented.

2022-04-26 15:13 UTC, jsmorgan42 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let originalPhrase = originalPhraseCell.staticTexts.firstMatch.label
Generally it's good practice with the Page Object Model architecture to not have to do this kind of cell logic in the test class. The test should just be able to call something like `MainScreen.firstPhraseCell` and `MainScreen.firstPhrase`. The whole idea being that all the logic to get the XCUIElement data is abstracted out into the screen or page class.

2022-04-26 15:13 UTC, jsmorgan42 commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let firstPhrase = firstPhraseCell.staticTexts.firstMatch.label
Same thing here

2022-04-26 15:33 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let originalPhrase = originalPhraseCell.staticTexts.firstMatch.label
Thanks, updated!

2022-04-26 15:48 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let originalPhrase = originalPhraseCell.staticTexts.firstMatch.label
Thanks, implemented!

2022-04-26 15:48 UTC, CananArikan commented on VocableUITests/Tests/PresetPhraseTests.swift
> +        let firstPhrase = firstPhraseCell.staticTexts.firstMatch.label
Updated!

2022-04-26 15:48 UTC, CananArikan commented on VocableUITests/Screens/BaseScreen.swift
> +        var flag = false
Updated!

2022-04-26 16:01 UTC, rhsalas3 approved these changes
💸 💸

2022-04-26 16:36 UTC, merged