[625] - Update Content strings.
willowtreeapps/eyespeak-ios pull request #630
Opened 2022-05-03 16:52 UTC by SashankPatel

closes 625

# Description of Work
Updated some strings suggested by content designer.

---

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"settings.alert.no_email_configured.title" = "Please add an email account to the %1$@ OS Mail app.";
```suggestion
"settings.alert.no_email_configured.title" = "Please sign into an account in %1$@ Mail";
```

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"category_editor.alert.cancel_editing_confirmation.title" = "If you close this without saving, your custom category will be deleted.";
```suggestion
"category_editor.alert.cancel_editing_confirmation.title" = "If you close without saving, the category will be deleted.";
```

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"text_editor.alert.cancel_editing_confirmation.title" = "If you exit now, your changes will not be saved.";
```suggestion
"text_editor.alert.cancel_editing_confirmation.title" = "If you close without saving, your changes will be lost.";
```

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"phrase_editor.alert.cancel_editing_confirmation.title" = "If you exit now, your changes will not be saved.";
```suggestion
"phrase_editor.alert.cancel_editing_confirmation.title" = "If you close without saving, your changes will be lost.";
```

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"listening_mode.empty_state.actively_listening.message" = "You are in listening mode. When someone asks a question out loud, Vocable will offer quick response options.";
This will read as:

```
[Listening Mode] <-- category

Listening...
You are in listening mode. When someone asks a question out loud, Vocable will offer quick response options.
```

I think we can drop "You are in listening mode"

2022-05-03 18:33 UTC, Clstroud commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"listening_mode.empty_state.free_response.message" = "Not sure what to suggest. Please repeat or use the Vocable keyboard or the phrases in categories to respond.";
1. "Please repeat" is tough because the person speaking may not be able to see the screen.
2. I'm not sure we have to specifically say "the Vocable keyboard" vs "keyboard"

How about:
```suggestion
"listening_mode.empty_state.free_response.message" = "Not sure what to suggest. Please use the keyboard or select an existing phrase to reply.";
```

2022-05-03 18:47 UTC, SashankPatel commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"settings.alert.no_email_configured.title" = "Please add an email account to the %1$@ OS Mail app.";
Can we say: Please sign into an account in the %1$@ Mail app?

2022-05-03 20:50 UTC, Clstroud approved these changes
💸 LGTM

2022-05-04 15:48 UTC, rhsalas3 commented
Testing on this branch, I found a few typos/errors in the implementation. 

I am pasting the parent ticket's description here with the original vs expected test, that now includes my notes on what does not pass verification.

We had a content writer (Julia Powers) review all of Vocable content and these were the edits she provided. 


| Original Text| Updated Text | Notes | Test Verified |
| ------------- | ------------- | -------------| -------------|
| "Not sure what to suggest. Please repeat or use the rest of Vocable to respond."  | Not sure what to suggest. Please repeat or use the Vocable keyboard or the phrases in categories to respond.  | Changed to add more context to the "the rest of vocable" | Implemented string does not match expected: "Not sure what to expect. Please use the keyboard or select an existing phrase to reply." I am not sure if this was already discussed; no trace of it here. Also, I think it would be better to still ask the user to repeat. ❌  |
| Vocable uses ARKit head tracking to detect the user's face as seen in the device's TrueDepth front camera feed for the purpose of controlling an on-screen pointer, allowing users with limited mobility to interact with the app. Head orientation and position data is used expressly for controlling the on-screen pointer. This data is not stored or transmitted in any way. Vocable needs permission to use the camera for this purpose.  | Vocable uses your device's front camera to detect minimal changes in head orientation and position. This allows users with limited mobility to control an on-screen pointer to interact with app. Camera data is used expressly for controlling the on-screen pointer. This data is not stored or transmitted in any way. Vocable needs permission to use the camera for this purpose.  | Reworked to remove run on sentence at the beginning | Typo found: "to interact with app." should be "to interact with the app." ❌  |

2022-05-04 15:54 UTC, rhsalas3 requested changes

2022-05-04 15:54 UTC, rhsalas3 commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"listening_mode.empty_state.free_response.message" = "Not sure what to suggest. Please use the keyboard or select an existing phrase to reply.";
The string implemented here does not match the expected string outlined in the AC of the parent ticket. 

Expected string: "Not sure what to suggest. Please repeat or use the Vocable keyboard or the phrases in categories to respond."

Personally I don't mind the current string, but would prefer to leave in the repeat part as a suggestion to the user. So in my opinion something like "Not sure what to suggest. Please repeat. You may also use the keyboard or select an existing phrase to reply."

2022-05-04 15:54 UTC, rhsalas3 commented on Vocable/Supporting Files/Info.plist
> +	<string>Vocable uses your device&apos;s front camera to detect minimal changes in head orientation and position. This allows users with limited mobility to control an on-screen pointer to interact w
There is a typo here, that also exists in the string spelled out w/in the AC. 

"to interact with app." should be updated to "to interact with the app."

I will also update the AC in the original ticket.

2022-05-04 16:00 UTC, SashankPatel commented on Vocable/Supporting Files/Info.plist
> +	<string>Vocable uses your device&apos;s front camera to detect minimal changes in head orientation and position. This allows users with limited mobility to control an on-screen pointer to interact w
Fixed.

2022-05-04 16:04 UTC, SashankPatel commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"listening_mode.empty_state.free_response.message" = "Not sure what to suggest. Please use the keyboard or select an existing phrase to reply.";
The thought behind removing the repeat, is the user asking the question is different than the user answering the question.  We geared this error towards the user answering the question, as the one asking may not be viewing the screen.

2022-05-04 16:47 UTC, rhsalas3 commented
Found an issue where the NSCameraUsageDescription key w/in InfoPlist.strings (English) was overriding the value set in `Info.plist`. This resulted in the body of the alert text for granting camera permissions to still contain the typo. 

To fix, we moved all of the text from `Info.plist` into the InfoPlist.strings file and referenced the .plist file's keys. This matches the implementation for other languages and fixes the issue.

@Clstroud and I mobbed on this so the changes are dev approved, and I tested them as well.

2022-05-04 16:47 UTC, rhsalas3 approved these changes

2022-05-04 16:47 UTC, rhsalas3 commented on Vocable/Supporting Files/en.lproj/Localizable.strings
> +"listening_mode.empty_state.free_response.message" = "Not sure what to suggest. Please use the keyboard or select an existing phrase to reply.";
haha literally just now having a chat with Chris about this and yes, I understand now the thought behind it. No change necessary for this one then.

2022-05-04 16:48 UTC, rhsalas3 commented
Tested and verified. As soon as the CircleCI job completes, this PR can be merged.

2022-05-04 17:28 UTC, merged