Automation/665 main screen ax ids
willowtreeapps/eyespeak-ios pull request #669
Opened 2022-05-17 17:18 UTC by rowildcard

Add accessibility Ids for Main Screen. 

---

2022-05-17 18:29 UTC, rhsalas3 requested changes
I re-enabled all tests locally to make sure they run and pass with the changes...they did 👍 💯 

Otherwise, there are a few code changes I would suggest.

2022-05-17 18:29 UTC, rhsalas3 commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +                cell?.accessibilityID = .settings.editCategories.addCategoryButton
I think this is the wrong identifier than what we intend. This button is the '+ Add Phrase' button on the Main Screen. It looks like we should add a new button identifier to `AccessibilityID+Root`, something like:
```
public static let addPhraseButton: AccessibilityID = "add-phrase-button"
```

Also the line is not aligned.

2022-05-17 18:29 UTC, rhsalas3 commented on Vocable/Supporting Files/AXIdentifier/AccessibilityID+Settings.swift
> +        public static let navBarBackButton: AccessibilityID = "settings-nav-bar-back-button"
I don't think we need this button in `Settings`. The `.shared.backButton` is the same button, which we use in our tests from the BaseScreen.

2022-05-17 18:29 UTC, rhsalas3 commented on VocableUITests/Screens/MainScreen.swift
> +    static let addPhraseLabel = XCUIApplication().cells[.settings.editCategories.addCategoryButton]
Per my previous comment on this PR, I think the accessibility ID should be for an add phrase button, instead of an add category button.  Since this is the Main Screen we should declare the button in shared:  `.root.addPhraseButton`. 

I also think it's a good opportunity here to rename the element to `addPhraseButton` here in MainScreen, since it's not a label.

2022-05-17 23:44 UTC, rowildcard commented on Vocable/Features/Root/CategoryDetailViewController.swift
> +                cell?.accessibilityID = .settings.editCategories.addCategoryButton
You are correct. This is just sloppy on my part. 😊

2022-05-17 23:44 UTC, rowildcard commented on Vocable/Supporting Files/AXIdentifier/AccessibilityID+Settings.swift
> +        public static let navBarBackButton: AccessibilityID = "settings-nav-bar-back-button"
Another good catch. 😊

2022-05-17 23:45 UTC, rowildcard commented on VocableUITests/Screens/MainScreen.swift
> +    static let addPhraseLabel = XCUIApplication().cells[.settings.editCategories.addCategoryButton]
I think I tried to get this PR out too quickly. 🤦‍♀️

2022-05-18 15:07 UTC, rhsalas3 commented on VocableUITests/Tests/CustomPhraseTests.swift
> +        _ = phraseQuery.element.waitForExistence(timeout: 2)
😉

2022-05-18 15:08 UTC, rhsalas3 approved these changes
LGTGTM!

💸 💸

2022-05-18 18:44 UTC, merged