Test/671 Settings Screen AX Ids
willowtreeapps/eyespeak-ios pull request #687
Opened 2022-05-27 19:12 UTC by CananArikan

closes #671 

**Description:**
Added identifiers for the Settings screen.

2022-05-27 21:22 UTC, rhsalas3 requested changes
Good work @CananArikan ! 

There are a few tweaks I think we should make though. Nothing too crazy 🤪

2022-05-27 21:22 UTC, rhsalas3 commented on Vocable/Features/Settings/SettingsViewController.swift
> +        }
I definitely like this better 😉   👍

2022-05-27 21:22 UTC, rhsalas3 commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let title = XCUIApplication().staticTexts[.shared.titleLabel]
Because this is a shared element, I think it should be moved to the `BaseScreen` class.

2022-05-27 21:22 UTC, rhsalas3 commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let contactDevelopersCell = XCUIApplication().cells[.settings.contactDevelopersCell]
We're missing the `listeningModeCell` element.

2022-05-27 21:22 UTC, rhsalas3 commented on VocableUITests/Screens/SettingsScreen.swift
>      static let settingsPageNextButton = XCUIApplication().buttons[.shared.pagination.nextButton]
There is already a button defined in `BaseScreen` for this element; using the `.shared.pagination.nextButton` identifier. We should go ahead and delete this one, as it's a duplicate.

2022-05-27 21:22 UTC, rhsalas3 commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let alertCancelButton = XCUIApplication().buttons[.shared.alert.cancelButton]
Since these elements are `.shared` we should move them to the `BaseScreen`.

2022-05-31 14:55 UTC, jsmorgan42 commented on Vocable/Features/Settings/SettingsViewController.swift
> +            }
Instead of the specifying the cases here, you can just say the default is an empty string

```suggestion
            default:
                return ""
```

2022-05-31 18:43 UTC, CananArikan commented on Vocable/Features/Settings/SettingsViewController.swift
> +            }
Thanks, updated!

2022-05-31 18:43 UTC, CananArikan commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let alertCancelButton = XCUIApplication().buttons[.shared.alert.cancelButton]
Moved!

2022-05-31 18:44 UTC, CananArikan commented on VocableUITests/Screens/SettingsScreen.swift
>      static let settingsPageNextButton = XCUIApplication().buttons[.shared.pagination.nextButton]
The duplicate element is deleted!

2022-05-31 18:44 UTC, CananArikan commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let contactDevelopersCell = XCUIApplication().cells[.settings.contactDevelopersCell]
Thanks, added.

2022-05-31 18:44 UTC, CananArikan commented on VocableUITests/Screens/SettingsScreen.swift
> +    static let title = XCUIApplication().staticTexts[.shared.titleLabel]
Done!

2022-05-31 18:48 UTC, jsmorgan42 approved these changes
Great work Canan! 💯 🥇

2022-05-31 18:53 UTC, rhsalas3 approved these changes
Woot! 🙌 

💸 💸

2022-05-31 18:53 UTC, rhsalas3 commented
Tested the changes on the branch, locally, by running `fastlane ios test`. All tests passed!

2022-05-31 19:11 UTC, merged